import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

        <body className={inter.className}>
        <header className="bg-white shadow">
            <nav className="container mx-auto px-6 py-3">
                <div className="flex justify-between items-center">
                    <div className="flex items-center">
                        <Link href={'/'} className="text-gray-600 text-xl font-semibold">University Database 1</Link>
                    </div>
                    <div className="flex items-center space-x-4">
                        <a href="/create-instructor" className="text-gray-600 hover:text-gray-800">Create Instructor</a>
                        <a href="/create-student" className="text-gray-600 hover:text-gray-800">Create Student</a>
                        <a href="/create-course" className="text-gray-600 hover:text-gray-800">Create Course</a>
                        <a href="/create-section" className="text-gray-600 hover:text-gray-800">Create Section</a>
                        <a href="/create-program" className="text-gray-600 hover:text-gray-800">Create Program</a>
                    </div>
                </div>
            </nav>
        </header>
        {children}
        </body>
        </html>
    );
}
